name: Build

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
